version: '3.9'

services:
  db:
    container_name: branch_db_prod
     # 1. Resource Limits on Prod DB
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  api:
    container_name: branch_api_prod
    environment:
     # 2. Structure JSON Logging
      FLASK_ENV: production
      
