services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - branchnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: branch_flaskapi
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
      PORT: 8000
      PYTHONPATH: /app
    networks:
      - branchnet
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: gunicorn -w 2 -b 0.0.0.0:8000 wsgi:app
  
  proxy:
    image: nginx:stable-alpine
    container_name: branch_proxy
    networks:
      - branchnet
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
 
    depends_on:
      api:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: branch_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - branchnet
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: branch_grafana
    ports:
      - "3000:3000"
    networks:
      - branchnet
    depends_on:
      - prometheus


volumes:
  db_data:
networks:
  branchnet:
    driver: bridge
