version: '3.8'
services:
  api:
    container_name: branch_api_dev
    # 1. Hot Reload
    volumes:
      - ./app:/app/app
    # command: gunicorn -w 2 -b 0.0.0.0:8000 --reload wsgi:app 
    environment:
      FLASK_ENV: development
  
  # 3. Small PostgreSQL Instance: No resource limits needed, so use default minimal resources
  db:
    container_name: branch_db_dev